### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by payallenka** [intrepidbird/hacking-crypto#1]
I would like to add Hill Cipher cryptography method to your project. This method uses matrix multiplication to encrypt and decrypt data.

**Comment by intrepidbird** [comment]
Sure! Make a PR!

**Comment by payallenka** [comment]
Kindly assign me the task and add the Hacktoberfest label to this issue.

**Comment by payallenka** [comment]
Kindly add Hacktoberfest-accepted tag to it.  Else it won’t be in count for my Hacktoberfest pull request.
